import { teamNames } from "./constants";
import { Intro } from "./types";

export const introData: Intro[] = [
  {
    name: teamNames.protagonist,
    designation: "Software Engineer",
    entryFrom: "left",
    introText: [
      `Hi there! Welcome, I'm… well, you. My name is ${teamNames.protagonist}.`,
      "I'm a afresh engineering grad with student debt and wide-eyed optimism.",
      "I truly believe hard work conquers all. Lucky, naive me - what could possibly go wrong?",
    ],
    image: "/characters/protagonist.png",
  },
  {
    name: teamNames.hr,
    designation: "HR",
    entryFrom: "right",
    introText: [
      `Hello! I'm ${teamNames.hr} from HR, here to give you the best onboarding experience.`,
      "My superpower is turning simple workplace issues into complex policy investigations.",
      "Remember, we're not just colleagues here, we're family...",
      "...and family sticks together through unpaid overtime.",
      "Let's start your onboarding process, and meet the team.",
    ],
    image: "/characters/hr.png",
  },
  {
    name: teamNames.ceo,
    designation: "CEO & CTO",
    entryFrom: "left",
    introText: [
      `Welcome aboard! I'm ${teamNames.ceo}, the CEO and CTO, I'm a Googler, I left Google but Google didn't leave me.`,
      "I believe in total freedom - while keeping a firm grip on every detail.",
      "Remember one thing, I know best, and opinions are just distractions.",
      "Expect perfection - no excuses, just results under my watchful eye.",
      "Follow my lead, and you might just survive. It's ethier my way or the highway.",
    ],
    image: "/characters/founder-1.png",
  },
  {
    name: teamNames.coo,
    designation: "COO & CPO",
    entryFrom: "right",
    introText: [
      `Hey hey! I'm ${teamNames.coo}, the laid-back COO and CPO.`,
      "I juggle genius ideas and big picture thinking - effortlessly, of course.",
      "I talk big visions, but why sweat the details when I've hired pros to handle my inbox and calls?",
      "Life's too short for stress; I just vibe and let the team sort it out.",
      "We're all family here - isn't that fab?",
    ],
    image: "/characters/founder-2.png",
  },
  {
    name: teamNames.engineeringManager,
    designation: "Engineering Manager",
    entryFrom: "left",
    introText: [
      `G'day! I'm ${teamNames.engineeringManager}, your globe-trotting Engineering Manager.`,
      "Autonomy is key - that's why my backlog is longer than the list of countries I've visited.",
      "My favourite game is blame and... let me just find a booth, I am actually on a train now.",
      "I swoop in at crunch time to claim the glory; it's all about strategic timing!",
      "Join the adventure; we'll manage... somehow.",
    ],
    image: "/characters/engineer-manager.png",
  },
  {
    name: teamNames.seniorEngineer,
    designation: "Senior Software Engineer",
    entryFrom: "right",
    introText: [
      `Hey! I'm ${teamNames.seniorEngineer}, the ultimate senior dev who lives for the company.`,
      "Family comes second. Also don't get me started on work life balance.",
      "I schedule everything on the corporate calendar, EVERYTHING; efficiency is my superpower!",
      "Sacrificing weekends? It's passion, not burnout - join me in the grind!",
      "Dedication like mine builds empires, lets get going, this is wasting my time.",
    ],
    image: "/characters/senior-engineer.png",
  },
  {
    name: teamNames.softwareEngineer,
    designation: "Software Engineer",
    entryFrom: "left",
    introText: [
      `Hi. I'm ${teamNames.softwareEngineer}, the silent shipper building from scratch without fanfare.`,
      "I know my stuff, aim for right choices, but politics? It drags you in anyway.",
      "Head down, code up - that's how real progress happens.",
      "Don't expect chit-chat; results speak louder.",
    ],
    image: "/characters/software-engineer.png",
  },
  {
    name: teamNames.juniorEngineer,
    designation: "Junior Software Engineer",
    entryFrom: "right",
    introText: [
      `Yo! I'm ${teamNames.juniorEngineer}, the ultimate junior engineer.`,
      "I'm here to help whenever, even if I'm a tad slow - but hey, language nuances are my jam!",
      "Good vibes only; let's build stuff without the rush.",
      "You're gonna love the team spirit here.",
    ],
    image: "/characters/junior-engineer.png",
  },
  {
    name: teamNames.technicalProgramManager,
    designation: "Technical Program Manager",
    entryFrom: "left",
    introText: [
      `Sup! I'm ${teamNames.technicalProgramManager}, not really sure about role yet, but the chillest guy ever`,
      "I kind of just creates mess for everyone to fix, Turning 3-day tasks into epic 8-week sagas.",
      "Why hustle when ChatGPT handles milestones and tickets? It's innovative efficiency!",
      "Six weeks in and only half done? That's just building suspense.",
      "Relax - it'll all land eventually.",
    ],
    image: "/characters/technical-program-manager.png",
  },
  {
    name: teamNames.productManager,
    designation: "Product Manager",
    entryFrom: "right",
    introText: [
      `What's up! I'm ${teamNames.productManager}, the PM with killer ideas that somehow get sidelined - but no biggie.`,
      "I'm your ride-or-die: defending you, saving face, and cursing for your own good.",
      "Cool under fire, always brainstorming; ignore the politics, focus on wins.",
      "Let's make magic happen, buddy.",
    ],
    image: "/characters/product-manager.png",
  },
  {
    name: teamNames.designer,
    designation: "UI/UX Designer",
    entryFrom: "left",
    introText: [
      `Hello! I'm ${teamNames.designer}, the design guru who adores teamwork...`,
      "...specially when I get to critique yours.",
      "Fonts and colors? That's my wheelhouse; who needs modern standards when my vision is timeless?",
      "I'm everyone's bestie upfront, but real magic happens behind the scenes.",
      "Let's create beauty - my way, of course!",
    ],
    image: "/characters/designer.png",
  },
];
